name: Buildroot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: submodule checkout
      run: |
        git submodule sync --recursive
        gitsubmodule update --init --force --recursive --depth=1
    - name: configure
      run: ./build.sh amd64_intel_kodi_defconfig
    - name: make
      run: ./build.sh all
